Don't put postgres data into home
stuvusIT/postgresql pull request #8
Opened 2017-10-07 17:55 UTC by dasJ

2017-10-07 21:10 UTC, SlothOfAnarchy requested changes

2017-10-07 21:10 UTC, SlothOfAnarchy commented on tasks/configure.yml
> +    - "/var/lib/postgresHome/.profile"
Please use a var for this, you can place it in the defaults.

2017-10-10 11:40 UTC, Scriptkiddi commented
pls rereview

2017-10-10 16:37 UTC, SlothOfAnarchy approved these changes

2017-10-10 16:40 UTC, merged

2017-10-14 19:56 UTC, dasJ commented
@Scriptkiddi Thanks for introducing an undocumented variable